services:
    reverse-proxy:
        image: traefik:v3.1 
        command:
            #enables webui for traefik
            - "--api.insecure=true"
            - "--providers.docker"
            #HTTP Redirect
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
            #https
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.leresolver.acme.tlschallenge=true"
            - "--certificatesresolvers.leresolver.acme.email=jack.charlesworth@proton.me"
            - "--certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./letsencrypt:/letsencrypt
        networks:
            - web
    mongo:
        image: mongo
        restart: always
        container_name: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - web
    backend:
        image: jackcharlesworth1/aspen-backend:latest
        labels:
            - "traefik.enable=true"
            - 'traefik.http.routers.backend.rule=Host("api.theaspenproject.cloud")'
            - "traefik.http.routers.backend.entrypoints=websecure"
            - "traefik.http.routers.backend.tls.certresolver=leresolver"
            - "traefik.http.services.backend.loadbalancer.server.port=7000"

        depends_on:
            - mongo
        env_file:
            - ./backend/.env
        networks:
            - web
        deploy:
            mode: replicated
            replicas: 3
    database_seeding:
        image: jackcharlesworth1/aspen-backend:latest
        command: node maintenance/addAdmin.js
        container_name: database_seeding
        depends_on:
            - backend
        env_file:
            - ./backend/.env
        networks:
           - web
    frontend:
        image: jackcharlesworth1/aspen-frontend:latest
        labels:
            - "traefik.enable=true"
            - 'traefik.http.routers.frontend.rule=Host("theaspenproject.cloud")'
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.routers.frontend.tls.certresolver=leresolver"
            - "traefik.http.services.frontend.loadbalancer.server.port=5173"
        depends_on:
            - backend
        networks:
            - web
        deploy:
          mode: replicated
          replicas: 3
volumes:
    mongo-data:
networks:
    web:
        external: false
